// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: db_base.proto

package db

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// flag 的值, 表示本条数据的操作状态
type OPERATE_TYPE int32

const (
	OPERATE_TYPE_OPERATE_NONE          OPERATE_TYPE = 0 //sql none
	OPERATE_TYPE_OPERATE_INSERT        OPERATE_TYPE = 1 //sql insert
	OPERATE_TYPE_OPERATE_UPDATE        OPERATE_TYPE = 2 //sql update
	OPERATE_TYPE_OPERATE_DELETE        OPERATE_TYPE = 3 //sql delete
	OPERATE_TYPE_OPERATE_LOAD          OPERATE_TYPE = 4 //sql load
	OPERATE_TYPE_OPERATE_DELETE_CACHE  OPERATE_TYPE = 5 //cache need delete
	OPERATE_TYPE_OPERATE_REPLACE       OPERATE_TYPE = 6
	OPERATE_TYPE_OPERATE_CALL_PROC     OPERATE_TYPE = 7 // call procedure
	OPERATE_TYPE_OPERATE_DELETE_BACKUP OPERATE_TYPE = 8 //backup it
)

// Enum value maps for OPERATE_TYPE.
var (
	OPERATE_TYPE_name = map[int32]string{
		0: "OPERATE_NONE",
		1: "OPERATE_INSERT",
		2: "OPERATE_UPDATE",
		3: "OPERATE_DELETE",
		4: "OPERATE_LOAD",
		5: "OPERATE_DELETE_CACHE",
		6: "OPERATE_REPLACE",
		7: "OPERATE_CALL_PROC",
		8: "OPERATE_DELETE_BACKUP",
	}
	OPERATE_TYPE_value = map[string]int32{
		"OPERATE_NONE":          0,
		"OPERATE_INSERT":        1,
		"OPERATE_UPDATE":        2,
		"OPERATE_DELETE":        3,
		"OPERATE_LOAD":          4,
		"OPERATE_DELETE_CACHE":  5,
		"OPERATE_REPLACE":       6,
		"OPERATE_CALL_PROC":     7,
		"OPERATE_DELETE_BACKUP": 8,
	}
)

func (x OPERATE_TYPE) Enum() *OPERATE_TYPE {
	p := new(OPERATE_TYPE)
	*p = x
	return p
}

func (x OPERATE_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OPERATE_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_db_base_proto_enumTypes[0].Descriptor()
}

func (OPERATE_TYPE) Type() protoreflect.EnumType {
	return &file_db_base_proto_enumTypes[0]
}

func (x OPERATE_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OPERATE_TYPE.Descriptor instead.
func (OPERATE_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_db_base_proto_rawDescGZIP(), []int{0}
}

type BS_RESULT_TYPE int32

const (
	BS_RESULT_TYPE_BS_RESULT_NONE    BS_RESULT_TYPE = 0 //
	BS_RESULT_TYPE_BS_RESULT_SUCCESS BS_RESULT_TYPE = 1
	BS_RESULT_TYPE_BS_RESULT_FAILED  BS_RESULT_TYPE = 2
)

// Enum value maps for BS_RESULT_TYPE.
var (
	BS_RESULT_TYPE_name = map[int32]string{
		0: "BS_RESULT_NONE",
		1: "BS_RESULT_SUCCESS",
		2: "BS_RESULT_FAILED",
	}
	BS_RESULT_TYPE_value = map[string]int32{
		"BS_RESULT_NONE":    0,
		"BS_RESULT_SUCCESS": 1,
		"BS_RESULT_FAILED":  2,
	}
)

func (x BS_RESULT_TYPE) Enum() *BS_RESULT_TYPE {
	p := new(BS_RESULT_TYPE)
	*p = x
	return p
}

func (x BS_RESULT_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BS_RESULT_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_db_base_proto_enumTypes[1].Descriptor()
}

func (BS_RESULT_TYPE) Type() protoreflect.EnumType {
	return &file_db_base_proto_enumTypes[1]
}

func (x BS_RESULT_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BS_RESULT_TYPE.Descriptor instead.
func (BS_RESULT_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_db_base_proto_rawDescGZIP(), []int{1}
}

var file_db_base_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         500000,
		Name:          "OptionTableId",
		Tag:           "varint,500000,opt,name=OptionTableId",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500001,
		Name:          "OptionTableName",
		Tag:           "bytes,500001,opt,name=OptionTableName",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500002,
		Name:          "OptionPrimaryKey",
		Tag:           "bytes,500002,opt,name=OptionPrimaryKey",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500003,
		Name:          "OptionForeignKey",
		Tag:           "bytes,500003,opt,name=OptionForeignKey",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500005,
		Name:          "OptionForeignReferences",
		Tag:           "bytes,500005,opt,name=OptionForeignReferences",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500006,
		Name:          "OptionAutoIncrementKey",
		Tag:           "bytes,500006,opt,name=OptionAutoIncrementKey",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500007,
		Name:          "OptionBackupTableName",
		Tag:           "bytes,500007,opt,name=OptionBackupTableName",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         500008,
		Name:          "OptionLoadOnly",
		Tag:           "varint,500008,opt,name=OptionLoadOnly",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500009,
		Name:          "OptionProcedureName",
		Tag:           "bytes,500009,opt,name=OptionProcedureName",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500010,
		Name:          "OptionProcedureResult",
		Tag:           "bytes,500010,opt,name=OptionProcedureResult",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500011,
		Name:          "OptionIndex",
		Tag:           "bytes,500011,opt,name=OptionIndex",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500012,
		Name:          "OptionUniqueKey",
		Tag:           "bytes,500012,opt,name=OptionUniqueKey",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         600000,
		Name:          "OptionRepeatLimit",
		Tag:           "varint,600000,opt,name=OptionRepeatLimit",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         600001,
		Name:          "OptionDBFieldExtra",
		Tag:           "bytes,600001,opt,name=OptionDBFieldExtra",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         600002,
		Name:          "OptionDBReadOnly",
		Tag:           "varint,600002,opt,name=OptionDBReadOnly",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         600003,
		Name:          "OptionDBNamePrefix",
		Tag:           "bytes,600003,opt,name=OptionDBNamePrefix",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         600004,
		Name:          "OptionDBLoadSql",
		Tag:           "bytes,600004,opt,name=OptionDBLoadSql",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         600005,
		Name:          "OptionDBNeedEscape",
		Tag:           "varint,600005,opt,name=OptionDBNeedEscape",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         600006,
		Name:          "OptionDBProcParam",
		Tag:           "varint,600006,opt,name=OptionDBProcParam",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         600007,
		Name:          "OptionOldName",
		Tag:           "bytes,600007,opt,name=OptionOldName",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         600008,
		Name:          "OptionTable",
		Tag:           "bytes,600008,opt,name=OptionTable",
		Filename:      "db_base.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         600009,
		Name:          "OptionBackUpTabel",
		Tag:           "bytes,600009,opt,name=OptionBackUpTabel",
		Filename:      "db_base.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional uint32 OptionTableId = 500000;
	E_OptionTableId = &file_db_base_proto_extTypes[0] //表ID
	// optional string OptionTableName = 500001;
	E_OptionTableName = &file_db_base_proto_extTypes[1] //表名
	// optional string OptionPrimaryKey = 500002;
	E_OptionPrimaryKey = &file_db_base_proto_extTypes[2] //主键
	// optional string OptionForeignKey = 500003;
	E_OptionForeignKey = &file_db_base_proto_extTypes[3] //外键
	// optional string OptionForeignReferences = 500005;
	E_OptionForeignReferences = &file_db_base_proto_extTypes[4] //外键的关联表
	// optional string OptionAutoIncrementKey = 500006;
	E_OptionAutoIncrementKey = &file_db_base_proto_extTypes[5] //自增长的Key
	// optional string OptionBackupTableName = 500007;
	E_OptionBackupTableName = &file_db_base_proto_extTypes[6] //备份表的名称
	// optional bool OptionLoadOnly = 500008;
	E_OptionLoadOnly = &file_db_base_proto_extTypes[7] //只用于数据加载
	// optional string OptionProcedureName = 500009;
	E_OptionProcedureName = &file_db_base_proto_extTypes[8] //存储过程名称
	// optional string OptionProcedureResult = 500010;
	E_OptionProcedureResult = &file_db_base_proto_extTypes[9] //存储过程返回结果的PB结构Name
	// optional string OptionIndex = 500011;
	E_OptionIndex = &file_db_base_proto_extTypes[10] //建立索引
	// optional string OptionUniqueKey = 500012;
	E_OptionUniqueKey = &file_db_base_proto_extTypes[11] //
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional uint32 OptionRepeatLimit = 600000;
	E_OptionRepeatLimit = &file_db_base_proto_extTypes[12] // repeat 字段限制的个数
	// optional string OptionDBFieldExtra = 600001;
	E_OptionDBFieldExtra = &file_db_base_proto_extTypes[13] // 创建数据库要用到得额外信息，如果没有该属性表示非数据库字段
	// optional bool OptionDBReadOnly = 600002;
	E_OptionDBReadOnly = &file_db_base_proto_extTypes[14] // 该字段对DB是否只读
	// optional string OptionDBNamePrefix = 600003;
	E_OptionDBNamePrefix = &file_db_base_proto_extTypes[15] // 数据库名称前缀
	// optional string OptionDBLoadSql = 600004;
	E_OptionDBLoadSql = &file_db_base_proto_extTypes[16] // 数据加载SQL语句
	// optional bool OptionDBNeedEscape = 600005;
	E_OptionDBNeedEscape = &file_db_base_proto_extTypes[17] // 字段是否需要转义存储
	// optional bool OptionDBProcParam = 600006;
	E_OptionDBProcParam = &file_db_base_proto_extTypes[18] // 是否存储过程参数
	// optional string OptionOldName = 600007;
	E_OptionOldName = &file_db_base_proto_extTypes[19] //用来自动修改字段名
	// optional string OptionTable = 600008;
	E_OptionTable = &file_db_base_proto_extTypes[20] // 建表名称
	// optional string OptionBackUpTabel = 600009;
	E_OptionBackUpTabel = &file_db_base_proto_extTypes[21] //备份表
)

var File_db_base_proto protoreflect.FileDescriptor

const file_db_base_proto_rawDesc = "" +
	"\n" +
	"\rdb_base.proto\x1a\x10descriptor.proto*\xcf\x01\n" +
	"\fOPERATE_TYPE\x12\x10\n" +
	"\fOPERATE_NONE\x10\x00\x12\x12\n" +
	"\x0eOPERATE_INSERT\x10\x01\x12\x12\n" +
	"\x0eOPERATE_UPDATE\x10\x02\x12\x12\n" +
	"\x0eOPERATE_DELETE\x10\x03\x12\x10\n" +
	"\fOPERATE_LOAD\x10\x04\x12\x18\n" +
	"\x14OPERATE_DELETE_CACHE\x10\x05\x12\x13\n" +
	"\x0fOPERATE_REPLACE\x10\x06\x12\x15\n" +
	"\x11OPERATE_CALL_PROC\x10\a\x12\x19\n" +
	"\x15OPERATE_DELETE_BACKUP\x10\b*Q\n" +
	"\x0eBS_RESULT_TYPE\x12\x12\n" +
	"\x0eBS_RESULT_NONE\x10\x00\x12\x15\n" +
	"\x11BS_RESULT_SUCCESS\x10\x01\x12\x14\n" +
	"\x10BS_RESULT_FAILED\x10\x02:J\n" +
	"\rOptionTableId\x12\x1f.google.protobuf.MessageOptions\x18\xa0\xc2\x1e \x01(\rR\rOptionTableId\x88\x01\x01:N\n" +
	"\x0fOptionTableName\x12\x1f.google.protobuf.MessageOptions\x18\xa1\xc2\x1e \x01(\tR\x0fOptionTableName\x88\x01\x01:P\n" +
	"\x10OptionPrimaryKey\x12\x1f.google.protobuf.MessageOptions\x18\xa2\xc2\x1e \x01(\tR\x10OptionPrimaryKey\x88\x01\x01:P\n" +
	"\x10OptionForeignKey\x12\x1f.google.protobuf.MessageOptions\x18\xa3\xc2\x1e \x01(\tR\x10OptionForeignKey\x88\x01\x01:^\n" +
	"\x17OptionForeignReferences\x12\x1f.google.protobuf.MessageOptions\x18\xa5\xc2\x1e \x01(\tR\x17OptionForeignReferences\x88\x01\x01:\\\n" +
	"\x16OptionAutoIncrementKey\x12\x1f.google.protobuf.MessageOptions\x18\xa6\xc2\x1e \x01(\tR\x16OptionAutoIncrementKey\x88\x01\x01:Z\n" +
	"\x15OptionBackupTableName\x12\x1f.google.protobuf.MessageOptions\x18\xa7\xc2\x1e \x01(\tR\x15OptionBackupTableName\x88\x01\x01:L\n" +
	"\x0eOptionLoadOnly\x12\x1f.google.protobuf.MessageOptions\x18\xa8\xc2\x1e \x01(\bR\x0eOptionLoadOnly\x88\x01\x01:V\n" +
	"\x13OptionProcedureName\x12\x1f.google.protobuf.MessageOptions\x18\xa9\xc2\x1e \x01(\tR\x13OptionProcedureName\x88\x01\x01:Z\n" +
	"\x15OptionProcedureResult\x12\x1f.google.protobuf.MessageOptions\x18\xaa\xc2\x1e \x01(\tR\x15OptionProcedureResult\x88\x01\x01:F\n" +
	"\vOptionIndex\x12\x1f.google.protobuf.MessageOptions\x18\xab\xc2\x1e \x01(\tR\vOptionIndex\x88\x01\x01:N\n" +
	"\x0fOptionUniqueKey\x12\x1f.google.protobuf.MessageOptions\x18\xac\xc2\x1e \x01(\tR\x0fOptionUniqueKey\x88\x01\x01:P\n" +
	"\x11OptionRepeatLimit\x12\x1d.google.protobuf.FieldOptions\x18\xc0\xcf$ \x01(\rR\x11OptionRepeatLimit\x88\x01\x01:R\n" +
	"\x12OptionDBFieldExtra\x12\x1d.google.protobuf.FieldOptions\x18\xc1\xcf$ \x01(\tR\x12OptionDBFieldExtra\x88\x01\x01:N\n" +
	"\x10OptionDBReadOnly\x12\x1d.google.protobuf.FieldOptions\x18\xc2\xcf$ \x01(\bR\x10OptionDBReadOnly\x88\x01\x01:R\n" +
	"\x12OptionDBNamePrefix\x12\x1d.google.protobuf.FieldOptions\x18\xc3\xcf$ \x01(\tR\x12OptionDBNamePrefix\x88\x01\x01:L\n" +
	"\x0fOptionDBLoadSql\x12\x1d.google.protobuf.FieldOptions\x18\xc4\xcf$ \x01(\tR\x0fOptionDBLoadSql\x88\x01\x01:R\n" +
	"\x12OptionDBNeedEscape\x12\x1d.google.protobuf.FieldOptions\x18\xc5\xcf$ \x01(\bR\x12OptionDBNeedEscape\x88\x01\x01:P\n" +
	"\x11OptionDBProcParam\x12\x1d.google.protobuf.FieldOptions\x18\xc6\xcf$ \x01(\bR\x11OptionDBProcParam\x88\x01\x01:H\n" +
	"\rOptionOldName\x12\x1d.google.protobuf.FieldOptions\x18\xc7\xcf$ \x01(\tR\rOptionOldName\x88\x01\x01:D\n" +
	"\vOptionTable\x12\x1d.google.protobuf.FieldOptions\x18\xc8\xcf$ \x01(\tR\vOptionTable\x88\x01\x01:P\n" +
	"\x11OptionBackUpTabel\x12\x1d.google.protobuf.FieldOptions\x18\xc9\xcf$ \x01(\tR\x11OptionBackUpTabel\x88\x01\x01B)H\x01Z%github.com/luyuancpp/dbprotooption;dbb\x06proto3"

var (
	file_db_base_proto_rawDescOnce sync.Once
	file_db_base_proto_rawDescData []byte
)

func file_db_base_proto_rawDescGZIP() []byte {
	file_db_base_proto_rawDescOnce.Do(func() {
		file_db_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_db_base_proto_rawDesc), len(file_db_base_proto_rawDesc)))
	})
	return file_db_base_proto_rawDescData
}

var file_db_base_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_db_base_proto_goTypes = []any{
	(OPERATE_TYPE)(0),                   // 0: OPERATE_TYPE
	(BS_RESULT_TYPE)(0),                 // 1: BS_RESULT_TYPE
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 3: google.protobuf.FieldOptions
}
var file_db_base_proto_depIdxs = []int32{
	2,  // 0: OptionTableId:extendee -> google.protobuf.MessageOptions
	2,  // 1: OptionTableName:extendee -> google.protobuf.MessageOptions
	2,  // 2: OptionPrimaryKey:extendee -> google.protobuf.MessageOptions
	2,  // 3: OptionForeignKey:extendee -> google.protobuf.MessageOptions
	2,  // 4: OptionForeignReferences:extendee -> google.protobuf.MessageOptions
	2,  // 5: OptionAutoIncrementKey:extendee -> google.protobuf.MessageOptions
	2,  // 6: OptionBackupTableName:extendee -> google.protobuf.MessageOptions
	2,  // 7: OptionLoadOnly:extendee -> google.protobuf.MessageOptions
	2,  // 8: OptionProcedureName:extendee -> google.protobuf.MessageOptions
	2,  // 9: OptionProcedureResult:extendee -> google.protobuf.MessageOptions
	2,  // 10: OptionIndex:extendee -> google.protobuf.MessageOptions
	2,  // 11: OptionUniqueKey:extendee -> google.protobuf.MessageOptions
	3,  // 12: OptionRepeatLimit:extendee -> google.protobuf.FieldOptions
	3,  // 13: OptionDBFieldExtra:extendee -> google.protobuf.FieldOptions
	3,  // 14: OptionDBReadOnly:extendee -> google.protobuf.FieldOptions
	3,  // 15: OptionDBNamePrefix:extendee -> google.protobuf.FieldOptions
	3,  // 16: OptionDBLoadSql:extendee -> google.protobuf.FieldOptions
	3,  // 17: OptionDBNeedEscape:extendee -> google.protobuf.FieldOptions
	3,  // 18: OptionDBProcParam:extendee -> google.protobuf.FieldOptions
	3,  // 19: OptionOldName:extendee -> google.protobuf.FieldOptions
	3,  // 20: OptionTable:extendee -> google.protobuf.FieldOptions
	3,  // 21: OptionBackUpTabel:extendee -> google.protobuf.FieldOptions
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	0,  // [0:22] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_db_base_proto_init() }
func file_db_base_proto_init() {
	if File_db_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_db_base_proto_rawDesc), len(file_db_base_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 22,
			NumServices:   0,
		},
		GoTypes:           file_db_base_proto_goTypes,
		DependencyIndexes: file_db_base_proto_depIdxs,
		EnumInfos:         file_db_base_proto_enumTypes,
		ExtensionInfos:    file_db_base_proto_extTypes,
	}.Build()
	File_db_base_proto = out.File
	file_db_base_proto_goTypes = nil
	file_db_base_proto_depIdxs = nil
}
